// SIZE OF EMPTY CLASS CAME OUT TO BE 1. IF IT WAS GIVEN 0 BYTE ,THEN WE WONT BE ABLE TO TRACK ITS EXISTANCE 

// ABSTRACTION AND ENCAPSULATION

// ENCAPSULATION IS A SUBSET OF ABSTRACTION. 
// ENCAPSULTAION : DATA HIDING 
// ABSTRACTION : IMPLEMENTAION HIDING
// ABSTRACTION ->
// ONLY SHOWING THE NECESSARY DETAILS TO THE USER
// ENCAPSULATION AND ABSTRACTION -> CAN BE ACHEIVED BY ACCESS MODIFIERS (PRIVATE, PUBLIC, PROTECTED)
// ENCAPSULATION AND ABSTRACTION OVERLAP IN MOST OF CASES

// TYPES OF INHERITANCE 

// SINGLE LEVEL INHERITANCE
// MULTILEVEL INHERITANCE
// MULTIPLE INHERITANCE
// HIERARCHICAL INHERITANCE
// HYBRID INHERITANCE

// POLYMORPHISM -> MANY FORMS
// TYPES OF POLYMORPHISM
// COMPILE TIME POLYMORPHISM -> FUNCTION OVERLOADING, OPERATOR OVERLOADING
// RUN TIME POLYMORPHISM -> FUNCTION OVERIDING